### ISSUE TITLE
Wizard Platformer Movement

### ISSUE THREAD

**Issue by BryanTai** [BryanTai/Support#1]
Make the Wizard controllable by using WASD key layout.

Make sure Jump is okay.

**Comment by napon** [comment]
There is probably a jump script out there for download - easier than writing everything from scratch

**Comment by BryanTai** [comment]
Found one

https://github.com/prime31/CharacterController2D

**Comment by Paul-Kijtapart** [comment]
Horizontal movement work with A = Left, D = Right.
Jump with W = up.

**Comment by napon** [comment]
Awesome stuff boys
