### ISSUE TITLE
Create Command Bubble

### ISSUE THREAD

**Issue by BryanTai** [BryanTai/Support#4]
Command Bubble summoned by Right Click

Circle area appears on screen for set amount of time (5 seconds?)

Can only have 1 bubble at a time.

Minions will respond to that bubble. Priority travel to get inside it.

**Comment by dan-l** [comment]
Bubble are created when mouse click on a certain pos(x,y) which is relative to the screen. Transform the x, y coordinates to be relative to the camera. 
Duration of the bubble is 5 but will transform to the newly clicked position

**Comment by dan-l** [comment]
implemented 2e0292e71c3bf9bafc5df77b4c8544dd3372e8ca
